#
# Makefile for the Linux kernel addon device drivers.
#

obj-y	+= pinctrl/
obj-y	+= video/fbdev/
obj-y	+= reset/
obj-y	+= mailbox/
obj-y	+= crypto/
obj-y	+= watchdog/
obj-y	+= virblk/
obj-y	+= clk/csky/
obj-y	+= pwm/
obj-y	+= gpu/drm/csky/
obj-y	+= npu/vip8000/
obj-y	+= pci/
obj-y	+= irqchip/
