#
# This enables the HDMI driver for C-SKY.
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-$(CONFIG_CSKY_HDMI) += csky_hdmi.o
obj-$(CONFIG_CSKY_DRM) += csky-drm-drv.o
obj-$(CONFIG_CSKY_DRM) += csky-drm-fb.o
obj-$(CONFIG_CSKY_DRM) += csky-drm-fbdev.o
obj-$(CONFIG_CSKY_DRM_HDMI) += csky-drm-hdmi.o
obj-$(CSKY_LCDC_CRTC) += csky-lcdc-crtc.o
obj-$(CSKY_LCDC_CRTC) += csky-drm-plane.o
