#
# This enables the HDMI driver for C-SKY.
# Makefile for the drm device driver.  This driver provides support for the
# Direct Rendering Infrastructure (DRI) in XFree86 4.1.0 and higher.

obj-$(CONFIG_CSKY_HDMI) += csky_hdmi.o